language: python
python:
  - "3.7"

branches:
  only:
    - main
    - recipe_api

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"